server:
  port: 443
  ssl:
    enabled: true
    key-alias: pasSSL
    key-store-password: password
    key-store: classpath:pas.p12
    key-store-type: PKCS12
    key-password: password

security:
  jwt:
    token:
      secret-key: 256970464e4d29792c4d2d24317256534d2d3039332a2b2e383929635f
